### PR TITLE
Added Support to Laravel 9 and Improved Docs

### PR DESCRIPTION
**Pull request by felipehertzer**
Hey, I added support to Laravel 9 and I also added a how to use on readme. Thanks.

I also added support to auto get phone_number or send anonymous notifications.

```
Notification::route("clicksend", $phonenumber)->notify(
   new MyNotification($message)
);
```

### CODE REVIEW

**Comment by felipehertzer** [comment]
Hey @developerdino can you look it? Thanks.

**Comment by developerdino** [comment]
Hi @felipehertzer, I'm really sorry about not getting to this sooner, I just didn't see the notification about it. I'll help to get this sorted and a new version out today for you.

And thanks for your contribution, I think these changes will be useful for everyone, we just need to fix the tests and I need to understand the reasoning behind your changes.

**Comment by felipehertzer** [comment]
Hi @developerdino, no worries, I sent an email [developers@verified.com.au](mailto:developers@verified.com.au) as well. 
Sorry for the tests, I just fixed it.
The changes:
- Changes on readme.
- Laravel 9 support.
- I added an empty constructor to be able to use methods without an initial message.

- Support to send sms without a model i.e.
```php
Notification::route("clicksend", $phonenumber)->notify(
   new MyNotification($message)
);
```
Also it is possible to send sms with a model i.e.
```php
$user->notify(
   new MyNotification($message)
);
```

**Comment by developerdino** [comment]
Any chance you could add a test for the On-demand notification functionality?

And fix up those style issues?

**Comment by felipehertzer** [comment]
Alright, done! I added the on demand test and attribute test, in the last case you can add an attribute $phone_number on the notification class to choose the number.

**Comment by developerdino** [comment]
@felipehertzer thanks for this PR and apologies again for not getting to this sooner. I'll try and find some time later today to do an official release.

**Comment by developerdino** [comment]
@felipehertzer FYI I've released version 1.0.0. Sorry for the delay.

**Pull request merged**
